categories:
  - sms
  - mms
  - whatsapp
  - rcs
  - number-lookup
  - verification
  - voice
  - video
  - tutorials
  - contributing-guidelines
  - atlas-platform
  - resources

filters:
  hostedFiles:
    baseUrl: https://sinch.github.io/docs/
