version: 2
jobs:
  push_master:
    docker:
      - image: circleci/node:10.16.1
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - run:
          name: push
          command: "DOCSVERSION=1.0 ./readme.js push"
  push_next:
    docker:
      - image: circleci/node:10.16.1
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - run:
          name: push
          command: "DOCSVERSION=9.9.9 ./readme.js push --prune"
  validate:
    docker:
      - image: circleci/node:10.16.1
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - run:
          name: validate
          command: "./readme.js validate --no-fail"

workflows:
  version: 2

  live:
    jobs:
      - hold:
          type: approval # manual approval
          filters:
            branches:
              only: master
      - push_master:
          requires:
            - hold
          filters:
            branches:
              only: master

  next:
    jobs:
      - validate
      - push_next:
          filters:
            branches:
              only: next