version: 2
jobs:
  push:
    docker:
      - image: circleci/node:10.16.1
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - run:
          name: push
          command: "DOCSVERSION=1.0 npx readme-sync push --prune"
  validate:
    docker:
      - image: circleci/node:10.16.1
    steps:
      - checkout
      - run:
          name: install-npm
          command: npm install
      - run:
          name: validate
          command: "npx readme-sync validate"

workflows:
  version: 2

  publish:
    jobs:
      - validate
      - push:
          requires:
            - validate
          filters:
            branches:
              only: master

  check:
    jobs:
      - validate:
          filters:
            branches:
              ignore: master
