# Validates changes in `docs` directory whenever changes are pushed to a branch or a pull request is submitted.
# This runs for all branches except master, since pushing on master is meant to trigger a publication to ReadMe, which is a different workflow.

name: Validate

on: 
  push:
    branches-ignore: 
    - "master"
    paths:
    - "docs/**"
  pull_request:
    paths: 
    - "docs/**"

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - run: npx readme-sync validate
